dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api"

	compileOnly project(":modules:employee:employee-api")
	
	implementation group: 'com.itextpdf', name: 'itextpdf', version: '5.5.13.3'
	
	implementation group: 'com.itextpdf.tool', name: 'xmlworker', version: '5.5.13.3'
	
	implementation group: 'com.itextpdf', name: 'layout', version: '7.2.3'
	
	testImplementation group: 'junit', name: 'junit', version: '4.13.2'

	implementation group: 'javax.mail', name: 'mail', version: '1.4.1'

	implementation group: 'com.google.code.gson', name: 'gson', version: '2.7'
	
}